FORMAT: 1A
HOST: http://RRR.apiblueprint.org/

# RRR

**Getting Names**

## All Information [/info]

### Questions [GET]

+ Response 200 (application/json)

        [
            {
                "info": "Whats the Name?",
                "choices": [
                    {
                        "name": "MIKE"
                    }, {
                        "name": "GEORGE"
                    }, {
                        "name": "SAMANTHA"
                    }, {
                        "name": "ALEX"
                    }
                ]
            }
        ]